AllCops:
  Excludes:
    - spec/*.rb
    - 'vendor/**/*'

Style/MutableConstant:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
