Style/MutableConstant:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
